var MonAn = [
    {
        title:'Gỏi cuốn',
        title2:'Gỏi cuốn - Việt Nam',
        mota1:'Gỏi cuốn là món ăn được ưa thích ở Nam Bộ, một món ăn ngon, bổ, rẻ, dễ thưởng thức và thực hiện. Chẳng tốn nhiều thời gian, chẳng cần một nơi sang trọng, chẳng phải tốn công tìm kiếm hay đắn đo về giá cả bạn đều có thể thưởng thức được món gỏi cuốn hấp dẫn. ',
        anh1:'/images/GoiCuon/goicuon1.jpg',
        tieude1:'Sức hút của ẩm thực gỏi cuốn',
        mota2:'Gỏi cuốn cùng các món cuộn, các món gỏi, nộm do tính chất tươi sống của rau nên cũng dễ ăn, là món khai vị, món ăn chơi rất tốt. Cắn một miếng gỏi cuốn, cảm nhận vị dai của bánh tráng, vị béo đậm đà của thịt ba chỉ trộn lẫn vị ngọt của tôm luộc, thêm một chút mặn mà của nước chấm, cái mát lạnh, cay nồng nơi đầu lưỡi của rau sống tạo thành một bản hợp tấu làm dậy lên các cung bậc vị giác.Gỏi cuốn có thể dùng làm điểm tâm sang, có thể là món ăn chơi buổi trưa… Từ người già đến người trẻ ai cũng có thể thưởng thức món ăn này.Trong những năm gần đây, ẩm thực Việt nhanh chóng được khẳng định có vị trí xứng đáng trong kho tàng văn hóa ẩm thực phong phú của nhân loại. Các món ngon Việt Nam tuy được biết đến muộn hơn các món của người Hoa, Thái, Ấn Độ nhưng khi đã được biết đến món ăn Việt người nước ngoài đều nhận thấy giá trị tinh tế và những ưu thế: không béo như món ăn người Hoa hay Indonesia, không cay như món Thái, không cao giá như món Nhật, dễ hợp khẩu vị hơn món Ấn Độ mà lại chứa nhiều tinh bột và rau xanh - hai chất các chuyên gia dinh dưỡng luôn khuyên dùng.Gỏi cuốn là món ăn rất được du khách yêu thích và muốn khám phá. Nên chăng, cần đưa món gỏi cuốn Nam Bộ vào các chương trình du lịch. Gỏi cuốn đại diện cho các món cuốn cũng đã làm cho thực khách nước ngoài tấm tắc trong những buổi tiệc buffet tổ chức trong các nhà hàng sang trọng. Gỏi cuốn hiện không chỉ có mặt trong tất cả nhà hàng Việt tại đây mà còn có trên thực đơn của các nhà hàng Hoa, Thái. Nhiều người Đan Mạch còn cho là nếu có một món ăn xuất xứ từ Đông Nam Á đủ khả năng cạnh tranh với sushi của Nhật, thì chính là gỏi cuốn một món ăn vừa ngon miệng, đủ chất dinh dưỡng mà lại không làm người ăn béo phì.Nếu phở được xem là đặc sản của các nhà hàng Việt chính cống thì hầu như nhà hàng Á nào cũng có món chả giò và gỏi cuốn. Cuốn chả giò Việt trong nhà hàng Hoa hay Thái bánh tráng dày, nhân không có cua, củ sắn được thay bằng giá và cà rốt. Riêng gỏi cuốn rất đa dạng khiến nhiều người Đan Mạch tưởng hễ cứ cuốn trong bánh tráng là thành gỏi cuốn. Trang ẩm thực của Thời báo Berlingske của Đan Mạch còn hướng dẫn cách làm gỏi cuốn Việt Nam với cà rốt cắt khúc và măng tây nguyên cọng, chấm nước mắm dấm!',
        anh2:'/images/GoiCuon/goicuon2.jpg',
        tieude2:'Dấu ấn thiên nhiên món gỏi cuốn',
        mota3:'Bánh tráng là nguyên liệu không thể thiếu trong món gỏi cuốn, là cái bao ngoài để gói các nguyên liệu bên trong của món gỏi cuốn. Bánh tráng có hình tròn, ngày nay còn có loại bánh hình chữ nhật. Trước khi gói nhúng bánh sơ qua nước cho bánh mền có thể dính chặt lại, cho nhân vào trong và có thể dính lại tại lớp ngoài cùng. Khi ăn có thể cảm nhận ngay các vị dai dai và mằn mặn của bánh tráng. Một màu trắng mỏng ẩn hiện bên trong là những nguyên liệu khác góp phần làm cho món gỏi cuốn thêm phần hấp dẫn.Thịt lợn thì tùy theo khẩu vị có thể dùng thịt chân giò hoặc thịt ba chỉ rút xương. Thịt heo ba chỉ và tôm là hai nguyên liệu chủ yếu của món gỏi cuốn Nam Bộ. Người ta chọn miếng thịt vừa có nạc, vừa có mỡ, luộc vừa chín tới, vớt ra tráng lại nước lạnh.Đôi khi cá cũng là nguyên liệu trong các món cuốn khác, gồm có món cá lóc nướng trui hay món cá điêu hồng, tai tượng chiên xù gói bánh tráng…Tôm chọn tôm tươi đem luộc, bóc vỏ. Tôm ngọt, màu đỏ gạch tạo cho món gỏi cuốn có màu sắc hết sức ấn tượng. Tôm đỏ gạch nằm cùng thịt heo nằm ẩn hiện trong lớp áo mỏng của bánh tráng. Làm cho thực khách phải tò mò dùng thử một miếng để cảm nhận hương vị.',
        anh3:'/images/GoiCuon/goicuon3.jpg',
        mota4:' Rau sống là gia vị hấp dẫn cho món gỏi cuốn. Các loại rau sống phổ biến nhất là: xà lách, dấp cá, rau thơm, hẹ. Tất cả được cho vào cùng với thịt heo ba chỉ, tôm luộc và không thể thiếu một chút bún tươi. Gỏi cuốn ngon một phần do nước chấm quyết định, lúc mới ra đời, gỏi cuốn chỉ ăn với mắm nêm, dần dần sáng tạo thêm nước mắm pha chua ngọt.'
    },
    {
        title:'Vịt Quay Bắc Kinh',
        title2:'Vịt Quay Bắc Kinh - Trung Quốc',
        mota1:'Gỏi cuốn là món ăn được ưa thích ở Nam Bộ, một món ăn ngon, bổ, rẻ, dễ thưởng thức và thực hiện. Chẳng tốn nhiều thời gian, chẳng cần một nơi sang trọng, chẳng phải tốn công tìm kiếm hay đắn đo về giá cả bạn đều có thể thưởng thức được món gỏi cuốn hấp dẫn. ',
        anh1:'/images/GoiCuon/goicuon1.jpg',
        tieude1:'Sức hút của ẩm thực gỏi cuốn',
        mota2:'Gỏi cuốn cùng các món cuộn, các món gỏi, nộm do tính chất tươi sống của rau nên cũng dễ ăn, là món khai vị, món ăn chơi rất tốt. Cắn một miếng gỏi cuốn, cảm nhận vị dai của bánh tráng, vị béo đậm đà của thịt ba chỉ trộn lẫn vị ngọt của tôm luộc, thêm một chút mặn mà của nước chấm, cái mát lạnh, cay nồng nơi đầu lưỡi của rau sống tạo thành một bản hợp tấu làm dậy lên các cung bậc vị giác.Gỏi cuốn có thể dùng làm điểm tâm sang, có thể là món ăn chơi buổi trưa… Từ người già đến người trẻ ai cũng có thể thưởng thức món ăn này.Trong những năm gần đây, ẩm thực Việt nhanh chóng được khẳng định có vị trí xứng đáng trong kho tàng văn hóa ẩm thực phong phú của nhân loại. Các món ngon Việt Nam tuy được biết đến muộn hơn các món của người Hoa, Thái, Ấn Độ nhưng khi đã được biết đến món ăn Việt người nước ngoài đều nhận thấy giá trị tinh tế và những ưu thế: không béo như món ăn người Hoa hay Indonesia, không cay như món Thái, không cao giá như món Nhật, dễ hợp khẩu vị hơn món Ấn Độ mà lại chứa nhiều tinh bột và rau xanh - hai chất các chuyên gia dinh dưỡng luôn khuyên dùng.Gỏi cuốn là món ăn rất được du khách yêu thích và muốn khám phá. Nên chăng, cần đưa món gỏi cuốn Nam Bộ vào các chương trình du lịch. Gỏi cuốn đại diện cho các món cuốn cũng đã làm cho thực khách nước ngoài tấm tắc trong những buổi tiệc buffet tổ chức trong các nhà hàng sang trọng. Gỏi cuốn hiện không chỉ có mặt trong tất cả nhà hàng Việt tại đây mà còn có trên thực đơn của các nhà hàng Hoa, Thái. Nhiều người Đan Mạch còn cho là nếu có một món ăn xuất xứ từ Đông Nam Á đủ khả năng cạnh tranh với sushi của Nhật, thì chính là gỏi cuốn một món ăn vừa ngon miệng, đủ chất dinh dưỡng mà lại không làm người ăn béo phì.Nếu phở được xem là đặc sản của các nhà hàng Việt chính cống thì hầu như nhà hàng Á nào cũng có món chả giò và gỏi cuốn. Cuốn chả giò Việt trong nhà hàng Hoa hay Thái bánh tráng dày, nhân không có cua, củ sắn được thay bằng giá và cà rốt. Riêng gỏi cuốn rất đa dạng khiến nhiều người Đan Mạch tưởng hễ cứ cuốn trong bánh tráng là thành gỏi cuốn. Trang ẩm thực của Thời báo Berlingske của Đan Mạch còn hướng dẫn cách làm gỏi cuốn Việt Nam với cà rốt cắt khúc và măng tây nguyên cọng, chấm nước mắm dấm!',
        anh2:'/images/GoiCuon/goicuon2.jpg',
        tieude2:'Dấu ấn thiên nhiên món gỏi cuốn',
        mota3:'Bánh tráng là nguyên liệu không thể thiếu trong món gỏi cuốn, là cái bao ngoài để gói các nguyên liệu bên trong của món gỏi cuốn. Bánh tráng có hình tròn, ngày nay còn có loại bánh hình chữ nhật. Trước khi gói nhúng bánh sơ qua nước cho bánh mền có thể dính chặt lại, cho nhân vào trong và có thể dính lại tại lớp ngoài cùng. Khi ăn có thể cảm nhận ngay các vị dai dai và mằn mặn của bánh tráng. Một màu trắng mỏng ẩn hiện bên trong là những nguyên liệu khác góp phần làm cho món gỏi cuốn thêm phần hấp dẫn.Thịt lợn thì tùy theo khẩu vị có thể dùng thịt chân giò hoặc thịt ba chỉ rút xương. Thịt heo ba chỉ và tôm là hai nguyên liệu chủ yếu của món gỏi cuốn Nam Bộ. Người ta chọn miếng thịt vừa có nạc, vừa có mỡ, luộc vừa chín tới, vớt ra tráng lại nước lạnh.Đôi khi cá cũng là nguyên liệu trong các món cuốn khác, gồm có món cá lóc nướng trui hay món cá điêu hồng, tai tượng chiên xù gói bánh tráng…Tôm chọn tôm tươi đem luộc, bóc vỏ. Tôm ngọt, màu đỏ gạch tạo cho món gỏi cuốn có màu sắc hết sức ấn tượng. Tôm đỏ gạch nằm cùng thịt heo nằm ẩn hiện trong lớp áo mỏng của bánh tráng. Làm cho thực khách phải tò mò dùng thử một miếng để cảm nhận hương vị.',
        anh3:'/images/GoiCuon/goicuon3.jpg',
        mota4:' Rau sống là gia vị hấp dẫn cho món gỏi cuốn. Các loại rau sống phổ biến nhất là: xà lách, dấp cá, rau thơm, hẹ. Tất cả được cho vào cùng với thịt heo ba chỉ, tôm luộc và không thể thiếu một chút bún tươi. Gỏi cuốn ngon một phần do nước chấm quyết định, lúc mới ra đời, gỏi cuốn chỉ ăn với mắm nêm, dần dần sáng tạo thêm nước mắm pha chua ngọt.'
    },
    {
        title:'Sushi',
        title2:'Sushi - Nhật Bản',
        mota1:'Gỏi cuốn là món ăn được ưa thích ở Nam Bộ, một món ăn ngon, bổ, rẻ, dễ thưởng thức và thực hiện. Chẳng tốn nhiều thời gian, chẳng cần một nơi sang trọng, chẳng phải tốn công tìm kiếm hay đắn đo về giá cả bạn đều có thể thưởng thức được món gỏi cuốn hấp dẫn. ',
        anh1:'/images/GoiCuon/goicuon1.jpg',
        tieude1:'Sức hút của ẩm thực gỏi cuốn',
        mota2:'Gỏi cuốn cùng các món cuộn, các món gỏi, nộm do tính chất tươi sống của rau nên cũng dễ ăn, là món khai vị, món ăn chơi rất tốt. Cắn một miếng gỏi cuốn, cảm nhận vị dai của bánh tráng, vị béo đậm đà của thịt ba chỉ trộn lẫn vị ngọt của tôm luộc, thêm một chút mặn mà của nước chấm, cái mát lạnh, cay nồng nơi đầu lưỡi của rau sống tạo thành một bản hợp tấu làm dậy lên các cung bậc vị giác.Gỏi cuốn có thể dùng làm điểm tâm sang, có thể là món ăn chơi buổi trưa… Từ người già đến người trẻ ai cũng có thể thưởng thức món ăn này.Trong những năm gần đây, ẩm thực Việt nhanh chóng được khẳng định có vị trí xứng đáng trong kho tàng văn hóa ẩm thực phong phú của nhân loại. Các món ngon Việt Nam tuy được biết đến muộn hơn các món của người Hoa, Thái, Ấn Độ nhưng khi đã được biết đến món ăn Việt người nước ngoài đều nhận thấy giá trị tinh tế và những ưu thế: không béo như món ăn người Hoa hay Indonesia, không cay như món Thái, không cao giá như món Nhật, dễ hợp khẩu vị hơn món Ấn Độ mà lại chứa nhiều tinh bột và rau xanh - hai chất các chuyên gia dinh dưỡng luôn khuyên dùng.Gỏi cuốn là món ăn rất được du khách yêu thích và muốn khám phá. Nên chăng, cần đưa món gỏi cuốn Nam Bộ vào các chương trình du lịch. Gỏi cuốn đại diện cho các món cuốn cũng đã làm cho thực khách nước ngoài tấm tắc trong những buổi tiệc buffet tổ chức trong các nhà hàng sang trọng. Gỏi cuốn hiện không chỉ có mặt trong tất cả nhà hàng Việt tại đây mà còn có trên thực đơn của các nhà hàng Hoa, Thái. Nhiều người Đan Mạch còn cho là nếu có một món ăn xuất xứ từ Đông Nam Á đủ khả năng cạnh tranh với sushi của Nhật, thì chính là gỏi cuốn một món ăn vừa ngon miệng, đủ chất dinh dưỡng mà lại không làm người ăn béo phì.Nếu phở được xem là đặc sản của các nhà hàng Việt chính cống thì hầu như nhà hàng Á nào cũng có món chả giò và gỏi cuốn. Cuốn chả giò Việt trong nhà hàng Hoa hay Thái bánh tráng dày, nhân không có cua, củ sắn được thay bằng giá và cà rốt. Riêng gỏi cuốn rất đa dạng khiến nhiều người Đan Mạch tưởng hễ cứ cuốn trong bánh tráng là thành gỏi cuốn. Trang ẩm thực của Thời báo Berlingske của Đan Mạch còn hướng dẫn cách làm gỏi cuốn Việt Nam với cà rốt cắt khúc và măng tây nguyên cọng, chấm nước mắm dấm!',
        anh2:'/images/GoiCuon/goicuon2.jpg',
        tieude2:'Dấu ấn thiên nhiên món gỏi cuốn',
        mota3:'Bánh tráng là nguyên liệu không thể thiếu trong món gỏi cuốn, là cái bao ngoài để gói các nguyên liệu bên trong của món gỏi cuốn. Bánh tráng có hình tròn, ngày nay còn có loại bánh hình chữ nhật. Trước khi gói nhúng bánh sơ qua nước cho bánh mền có thể dính chặt lại, cho nhân vào trong và có thể dính lại tại lớp ngoài cùng. Khi ăn có thể cảm nhận ngay các vị dai dai và mằn mặn của bánh tráng. Một màu trắng mỏng ẩn hiện bên trong là những nguyên liệu khác góp phần làm cho món gỏi cuốn thêm phần hấp dẫn.Thịt lợn thì tùy theo khẩu vị có thể dùng thịt chân giò hoặc thịt ba chỉ rút xương. Thịt heo ba chỉ và tôm là hai nguyên liệu chủ yếu của món gỏi cuốn Nam Bộ. Người ta chọn miếng thịt vừa có nạc, vừa có mỡ, luộc vừa chín tới, vớt ra tráng lại nước lạnh.Đôi khi cá cũng là nguyên liệu trong các món cuốn khác, gồm có món cá lóc nướng trui hay món cá điêu hồng, tai tượng chiên xù gói bánh tráng…Tôm chọn tôm tươi đem luộc, bóc vỏ. Tôm ngọt, màu đỏ gạch tạo cho món gỏi cuốn có màu sắc hết sức ấn tượng. Tôm đỏ gạch nằm cùng thịt heo nằm ẩn hiện trong lớp áo mỏng của bánh tráng. Làm cho thực khách phải tò mò dùng thử một miếng để cảm nhận hương vị.',
        anh3:'/images/GoiCuon/goicuon3.jpg',
        mota4:' Rau sống là gia vị hấp dẫn cho món gỏi cuốn. Các loại rau sống phổ biến nhất là: xà lách, dấp cá, rau thơm, hẹ. Tất cả được cho vào cùng với thịt heo ba chỉ, tôm luộc và không thể thiếu một chút bún tươi. Gỏi cuốn ngon một phần do nước chấm quyết định, lúc mới ra đời, gỏi cuốn chỉ ăn với mắm nêm, dần dần sáng tạo thêm nước mắm pha chua ngọt.'
    }
]

module.exports = MonAn;