var pageTT = [
    {
        title:'Dừng, dời nhiều lễ hội vì ảnh hưởng của dịch Covid-19',
        head1:'Dừng hoặc dời nhiều lễ hội ở Việt Nam sang thời điểm khác như: Lễ hội Áo dài sẽ dời qua tháng 10, tổ chức online; Sapa đổi thời gian Lễ hội hoa hồng và dừng Lễ hội mùa Thu (Bát Xát)',
        mota1:'Bà Nguyễn Thị Ánh Hoa, Phó Giám đốc thường trực Sở Du lịch TP HCM cho biết, đơn vị đang lấy ý kiến từ các chuyên gia, ban ngành để chuyển đổi phương cách tổ chức Lễ hội Áo dài TP HCM lần thứ 7 năm 2020 sang hình thức online. "Dự kiến, nếu mọi thứ chuẩn bị kịp, Lễ hội sẽ được diễn ra vào tháng 10", bà Hoa nói.',
        anh1:'/images/TinTuc1/TT1.jpg',
        mota2:'Ông Hoàng Văn Tuyên, Chủ tịch Hiệp hội du lịch Lào Cai cũng cho biết, Lễ hội mùa Thu "Y Tý đại ngàn" và Ngày hội văn hóa thể thao các dân tộc huyện Bát Xát, tỉnh Lào Cai dự kiến tổ chức từ ngày 15 - 16/8 tại xã Y Tý với rất nhiều hoạt động hấp dẫn, mang đậm bản sắc văn hóa các dân tộc sẽ phải dừng để đảm bảo công tác phòng chống dịch bệnh.',
        anh2:'/images/TinTuc1/TT2.jpg',
        mota3:'Lễ hội hoa hồng và rượu vang Sapa 2020, theo kế hoạch được tổ chức từ 21 - 23/8 tại thị xã Sapa, tỉnh Lào Cai. Chương trình đã chuyển thời gian,dự kiến diễn ra tháng 10/2020 với các hoạt động như trưng bày hoa hồng theo chủ đề Con đường tình yêu, vườn hoa Sapa, chợ hoa, phố hoa...."Lễ hội hoa hồng và rượu vang Sapa năm nay, trước mắt dự kiến sẽ dời sang tháng 10 để để đảm bảo công tác phòng chống dịch bệnh Covid-19. Đến thời điểm đó, tùy tình hình diễn biến của dịch mới tiếp tục có tổ chức hay không. Nếu dịch bệnh vẫn còn diễn biến khó lường, có thể cả Lễ hội mùa Đông (diễn ra vào tháng 11) cũng sẽ tạm hoãn", ông Tuyên nói.',
        anh3:'/images/TinTuc1/TT3.jpg',
        mota4:'UBND tỉnh Đăk Lăk cũng cho biết, do tình hình dịch Covid-19, Chính phủ đã đồng ý dừng tổ chức Lễ hội Cà phê Buôn Ma Thuột lần thứ 8 năm 2021 và đề xuất dời sang năm 2022. Lễ hội cà phê Buôn Ma Thuột là sự kiện mang tầm quốc gia, được tổ chức định kỳ hai năm một lần nhằm quảng bá hình ảnh Buôn Ma Thuột, Đăk Lăk là vùng đất Tây Nguyên huyền thoại, giàu bản sắc dân tộc. Theo kế hoạch, lễ hội được tổ chức từ ngày 9 - 16/3/2021 với nhiều hoạt động. Lễ hội cà phê Buôn Ma Thuột lần thứ 7 năm 2019 đã đón tiếp 444 đại biểu trong nước, 158 khách nước ngoài đến từ 25 đoàn và thu hút hơn 50 nghìn lượt khách du lịch, trong đó có gần 6.000 lượt khách quốc tế tham quan, thưởng lãm.'
    },
    {
        title:'Đây là mẫu tin tức thứ 2',
        head1:'Dừng hoặc dời nhiều lễ hội ở Việt Nam sang thời điểm khác như: Lễ hội Áo dài sẽ dời qua tháng 10, tổ chức online; Sapa đổi thời gian Lễ hội hoa hồng và dừng Lễ hội mùa Thu (Bát Xát)',
        mota1:'Bà Nguyễn Thị Ánh Hoa, Phó Giám đốc thường trực Sở Du lịch TP HCM cho biết, đơn vị đang lấy ý kiến từ các chuyên gia, ban ngành để chuyển đổi phương cách tổ chức Lễ hội Áo dài TP HCM lần thứ 7 năm 2020 sang hình thức online. "Dự kiến, nếu mọi thứ chuẩn bị kịp, Lễ hội sẽ được diễn ra vào tháng 10", bà Hoa nói.',
        anh1:'/images/TinTuc1/TT1.jpg',
        mota2:'Ông Hoàng Văn Tuyên, Chủ tịch Hiệp hội du lịch Lào Cai cũng cho biết, Lễ hội mùa Thu "Y Tý đại ngàn" và Ngày hội văn hóa thể thao các dân tộc huyện Bát Xát, tỉnh Lào Cai dự kiến tổ chức từ ngày 15 - 16/8 tại xã Y Tý với rất nhiều hoạt động hấp dẫn, mang đậm bản sắc văn hóa các dân tộc sẽ phải dừng để đảm bảo công tác phòng chống dịch bệnh.',
        anh2:'/images/TinTuc1/TT2.jpg',
        mota3:'Lễ hội hoa hồng và rượu vang Sapa 2020, theo kế hoạch được tổ chức từ 21 - 23/8 tại thị xã Sapa, tỉnh Lào Cai. Chương trình đã chuyển thời gian,dự kiến diễn ra tháng 10/2020 với các hoạt động như trưng bày hoa hồng theo chủ đề Con đường tình yêu, vườn hoa Sapa, chợ hoa, phố hoa.... "Lễ hội hoa hồng và rượu vang Sapa năm nay, trước mắt dự kiến sẽ dời sang tháng 10 để để đảm bảo công tác phòng chống dịch bệnh Covid-19. Đến thời điểm đó, tùy tình hình diễn biến của dịch mới tiếp tục có tổ chức hay không. Nếu dịch bệnh vẫn còn diễn biến khó lường, có thể cả Lễ hội mùa Đông (diễn ra vào tháng 11) cũng sẽ tạm hoãn", ông Tuyên nói.',
        anh3:'/images/TinTuc1/TT3.jpg',
        mota4:'UBND tỉnh Đăk Lăk cũng cho biết, do tình hình dịch Covid-19, Chính phủ đã đồng ý dừng tổ chức Lễ hội Cà phê Buôn Ma Thuột lần thứ 8 năm 2021 và đề xuất dời sang năm 2022. Lễ hội cà phê Buôn Ma Thuột là sự kiện mang tầm quốc gia, được tổ chức định kỳ hai năm một lần nhằm quảng bá hình ảnh Buôn Ma Thuột, Đăk Lăk là vùng đất Tây Nguyên huyền thoại, giàu bản sắc dân tộc. Theo kế hoạch, lễ hội được tổ chức từ ngày 9 - 16/3/2021 với nhiều hoạt động. Lễ hội cà phê Buôn Ma Thuột lần thứ 7 năm 2019 đã đón tiếp 444 đại biểu trong nước, 158 khách nước ngoài đến từ 25 đoàn và thu hút hơn 50 nghìn lượt khách du lịch, trong đó có gần 6.000 lượt khách quốc tế tham quan, thưởng lãm.'
    },
    {
        title:'Đây là mẫu tin tức thứ 3',
        head1:'Dừng hoặc dời nhiều lễ hội ở Việt Nam sang thời điểm khác như: Lễ hội Áo dài sẽ dời qua tháng 10, tổ chức online; Sapa đổi thời gian Lễ hội hoa hồng và dừng Lễ hội mùa Thu (Bát Xát)',
        mota1:'Bà Nguyễn Thị Ánh Hoa, Phó Giám đốc thường trực Sở Du lịch TP HCM cho biết, đơn vị đang lấy ý kiến từ các chuyên gia, ban ngành để chuyển đổi phương cách tổ chức Lễ hội Áo dài TP HCM lần thứ 7 năm 2020 sang hình thức online. "Dự kiến, nếu mọi thứ chuẩn bị kịp, Lễ hội sẽ được diễn ra vào tháng 10", bà Hoa nói.',
        anh1:'/images/TinTuc1/TT1.jpg',
        mota2:'Ông Hoàng Văn Tuyên, Chủ tịch Hiệp hội du lịch Lào Cai cũng cho biết, Lễ hội mùa Thu "Y Tý đại ngàn" và Ngày hội văn hóa thể thao các dân tộc huyện Bát Xát, tỉnh Lào Cai dự kiến tổ chức từ ngày 15 - 16/8 tại xã Y Tý với rất nhiều hoạt động hấp dẫn, mang đậm bản sắc văn hóa các dân tộc sẽ phải dừng để đảm bảo công tác phòng chống dịch bệnh.',
        anh2:'/images/TinTuc1/TT2.jpg',
        mota3:'Lễ hội hoa hồng và rượu vang Sapa 2020, theo kế hoạch được tổ chức từ 21 - 23/8 tại thị xã Sapa, tỉnh Lào Cai. Chương trình đã chuyển thời gian,dự kiến diễn ra tháng 10/2020 với các hoạt động như trưng bày hoa hồng theo chủ đề Con đường tình yêu, vườn hoa Sapa, chợ hoa, phố hoa.... "Lễ hội hoa hồng và rượu vang Sapa năm nay, trước mắt dự kiến sẽ dời sang tháng 10 để để đảm bảo công tác phòng chống dịch bệnh Covid-19. Đến thời điểm đó, tùy tình hình diễn biến của dịch mới tiếp tục có tổ chức hay không. Nếu dịch bệnh vẫn còn diễn biến khó lường, có thể cả Lễ hội mùa Đông (diễn ra vào tháng 11) cũng sẽ tạm hoãn", ông Tuyên nói.',
        anh3:'/images/TinTuc1/TT3.jpg',
        mota4:'UBND tỉnh Đăk Lăk cũng cho biết, do tình hình dịch Covid-19, Chính phủ đã đồng ý dừng tổ chức Lễ hội Cà phê Buôn Ma Thuột lần thứ 8 năm 2021 và đề xuất dời sang năm 2022. Lễ hội cà phê Buôn Ma Thuột là sự kiện mang tầm quốc gia, được tổ chức định kỳ hai năm một lần nhằm quảng bá hình ảnh Buôn Ma Thuột, Đăk Lăk là vùng đất Tây Nguyên huyền thoại, giàu bản sắc dân tộc. Theo kế hoạch, lễ hội được tổ chức từ ngày 9 - 16/3/2021 với nhiều hoạt động. Lễ hội cà phê Buôn Ma Thuột lần thứ 7 năm 2019 đã đón tiếp 444 đại biểu trong nước, 158 khách nước ngoài đến từ 25 đoàn và thu hút hơn 50 nghìn lượt khách du lịch, trong đó có gần 6.000 lượt khách quốc tế tham quan, thưởng lãm.'
    }
]
module.exports = pageTT;